enemy:
  color:
  - 255
  - 0
  - 0
  damage: 10
  damage_interval: 1.0
  health: 50
  size: 15
  speed: 100
game:
  fps: 60
  survival_time: 30
  window_height: 800
  window_width: 1200
items:
  ammo:
    color:
    - 0
    - 255
    - 255
    damage: 25
    radius: 100
    size: 10
    symbol: ⚡
  health:
    color:
    - 255
    - 255
    - 0
    heal_amount: 30
    size: 10
    symbol: ➕
player:
  color:
  - 0
  - 255
  - 0
  max_health: 100
  size: 20
  speed: 200
spawn:
  ammo_items_per_area: 1
  enemies_per_area: 5
  health_items_per_area: 2
world:
  activation_distance: 50
  area_size: 400
  grid_size: 3
  max_active_areas: 4
