enemy:
  color:
  - 255
  - 0
  - 0
  damage: 20
  damage_interval: 1.0
  health: 30
  size: 15
  speed: 120
game:
  fps: 60
  survival_time: 60
  window_height: 800
  window_width: 1200
items:
  ammo:
    color:
    - 0
    - 255
    - 255
    damage: 50
    radius: 150
    size: 10
    symbol: ⚡
  health:
    color:
    - 255
    - 255
    - 0
    heal_amount: 30
    size: 10
    symbol: ➕
player:
  color:
  - 0
  - 255
  - 0
  max_health: 150
  size: 20
  speed: 300
spawn:
  ammo_items_per_area: 1
  enemies_per_area: 50
  health_items_per_area: 1
world:
  activation_distance: 150
  area_size: 800
  grid_size: 3
  max_active_areas: 6
