enemy:
  color:
  - 255
  - 0
  - 0
  damage: 5
  damage_interval: 1.0
  health: 20
  size: 15
  speed: 80
game:
  fps: 30
  survival_time: 30
  window_height: 800
  window_width: 1200
items:
  ammo:
    color:
    - 0
    - 255
    - 255
    damage: 100
    radius: 200
    size: 10
    symbol: ⚡
  health:
    color:
    - 255
    - 255
    - 0
    heal_amount: 30
    size: 10
    symbol: ➕
player:
  color:
  - 0
  - 255
  - 0
  max_health: 200
  size: 20
  speed: 400
spawn:
  ammo_items_per_area: 5
  enemies_per_area: 200
  health_items_per_area: 5
world:
  activation_distance: 200
  area_size: 1000
  grid_size: 3
  max_active_areas: 9
